<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('conjunction_alerts', function (Blueprint $table) {
            // 'sgp4' = generated by conjunctions:check from local TLE screening
            // 'space_track_cdm' = sourced from a real Space-Track CDM event
            // null = legacy alerts created before this column was added
            $table->string('source', 30)->nullable()->after('risk_score');

            // Reference to the CDM event that generated this alert (nullable).
            // Null for SGP4-sourced alerts or legacy alerts.
            $table->foreignId('conjunction_event_id')
                ->nullable()
                ->after('source')
                ->constrained('conjunction_events')
                ->nullOnDelete()
                ->index();
        });
    }

    public function down(): void
    {
        Schema::table('conjunction_alerts', function (Blueprint $table) {
            $table->dropForeign(['conjunction_event_id']);
            $table->dropColumn(['source', 'conjunction_event_id']);
        });
    }
};
