---
- name: Install Nginx and Certbot
  apt:
    name:
      - nginx
      - certbot
      - python3-certbot-nginx
    state: present
    update_cache: yes

- name: Enable and start Nginx
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: Copy Nginx proxy config
  template:
    src: satview.conf.j2
    dest: /etc/nginx/sites-available/satview
    mode: '0644'

- name: Enable site
  file:
    src: /etc/nginx/sites-available/satview
    dest: /etc/nginx/sites-enabled/satview
    state: link

- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Reload Nginx
  systemd:
    name: nginx
    state: reloaded
