<?php

namespace App\Http\Middleware;

use App\Models\ApiKey;
use App\Models\ApiUsage;
use App\Models\GuestUsage;
use App\Services\EntitlementService;
use Closure;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * Unified actor resolution for public satellite/conjunction endpoints.
 *
 * Priority:
 *   1. Bearer token  → Sanctum user   (unlimited web requests, plan-based capabilities)
 *   2. X-API-Key     → API key        (tier-based daily limit, tracked in api_usage)
 *   3. No auth       → Guest session  (10 requests/day, identified by X-Guest-ID or IP)
 *
 * Sets request attributes: actor_type (user|api_key|guest), actor, entitlements
 */
class HandlePublicRequest
{
    public function handle(Request $request, Closure $next): Response
    {
        // 1. Bearer token → try customer Sanctum guard, then admin guard.
        // If the token is expired or invalid both guards return null and we fall through to the
        // guest path. This is intentional: the globe/tracker remain usable with a stale session.
        if ($request->bearerToken()) {
            $user = auth('sanctum')->user();
            if ($user) {
                $request->attributes->set('actor_type', 'user');
                $request->attributes->set('actor', $user);
                $request->attributes->set('entitlements', EntitlementService::forUser($user));

                return $next($request);
            }

            // Admin tokens have tokenable_type=AdminAccount and are rejected by the 'sanctum'
            // (users) guard above. Try the 'admin' guard so logged-in admins bypass guest limits.
            $admin = auth('admin')->user();
            if ($admin) {
                $request->attributes->set('actor_type', 'admin');
                $request->attributes->set('actor', $admin);
                $request->attributes->set('entitlements', EntitlementService::forAdmin());

                return $next($request);
            }
        }

        // 2. API key header or query param
        $rawKey = $request->header('X-API-Key') ?? $request->query('api_key');
        if ($rawKey) {
            return $this->handleApiKey($request, $next, $rawKey);
        }

        // 3. Guest (anonymous)
        return $this->handleGuest($request, $next);
    }

    private function handleApiKey(Request $request, Closure $next, string $rawKey): Response
    {
        $apiKey = ApiKey::where('key', $rawKey)->whereNull('deleted_at')->first();

        if (! $apiKey) {
            return $this->error('Invalid API key', 'INVALID_API_KEY', 401);
        }

        if ($apiKey->expires_at && $apiKey->expires_at->isPast()) {
            return $this->error('API key expired', 'API_KEY_EXPIRED', 401);
        }

        $used = $apiKey->todayUsageCount();

        if ($apiKey->daily_limit !== null && $used >= $apiKey->daily_limit) {
            return $this->error('Daily rate limit exceeded', 'RATE_LIMIT_EXCEEDED', 429, [
                'limit'       => $apiKey->daily_limit,
                'used'        => $used,
                'reset_at'    => now()->endOfDay()->toIso8601String(),
                'upgrade_url' => url('/billing'),
            ]);
        }

        $apiKey->update(['last_used_at' => now()]);

        $request->attributes->set('actor_type', 'api_key');
        $request->attributes->set('actor', $apiKey);
        $request->attributes->set('entitlements', EntitlementService::forApiKey($apiKey));

        $start    = microtime(true);
        $response = $next($request);
        $ms       = (int) round((microtime(true) - $start) * 1000);

        ApiUsage::create([
            'api_key_id'  => $apiKey->id,
            'endpoint'    => $request->path(),
            'method'      => $request->method(),
            'status_code' => $response->getStatusCode(),
            'response_ms' => $ms,
            'ip'          => $request->ip(),
        ]);

        $remaining = $apiKey->daily_limit !== null
            ? max(0, $apiKey->daily_limit - $used - 1)
            : PHP_INT_MAX;

        $response->headers->set('X-RateLimit-Limit', (string) ($apiKey->daily_limit ?? 'unlimited'));
        $response->headers->set('X-RateLimit-Remaining', (string) $remaining);
        $response->headers->set('X-RateLimit-Reset', (string) now()->endOfDay()->timestamp);
        $response->headers->set('X-API-Tier', $apiKey->tier);

        return $response;
    }

    private function handleGuest(Request $request, Closure $next): Response
    {
        $entitlements = EntitlementService::forGuest();
        $limit        = $entitlements['requests_per_day'];

        // Identify guest: prefer UUID from header (generated by frontend), fall back to IP
        $identifier = $request->header('X-Guest-ID') ?: $request->ip();

        $used = GuestUsage::todayCount($identifier);

        if ($used >= $limit) {
            return $this->error(
                "You've used your {$limit} free analyses today. Create a free account to continue.",
                'GUEST_LIMIT_REACHED',
                429,
                [
                    'limit'       => $limit,
                    'used'        => $used,
                    'reset_at'    => now()->endOfDay()->toIso8601String(),
                    'upgrade_url' => '/register',
                ]
            );
        }

        GuestUsage::record($identifier);

        $request->attributes->set('actor_type', 'guest');
        $request->attributes->set('actor', null);
        $request->attributes->set('entitlements', $entitlements);

        $response = $next($request);
        $response->headers->set('X-Guest-Limit', (string) $limit);
        $response->headers->set('X-Guest-Requests-Remaining', (string) max(0, $limit - $used - 1));

        return $response;
    }

    private function error(string $message, string $code, int $status, array $details = []): Response
    {
        return response()->json([
            'success' => false,
            'data'    => null,
            'error'   => [
                'code'    => $code,
                'message' => $message,
                'details' => $details,
            ],
        ], $status);
    }
}
